version: '3.8'

services:
  dsko:
    image: spring-server:latest
    container_name: spring-server-container
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
    networks:
      - dsko-network

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - dsko-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-container
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - dsko-network
    depends_on:
      - dsko

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-container
    ports:
      - "3001:3000" # Changed to 3001 to avoid conflict with local Grafana
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - dsko-network

volumes:
  redis_data:
  grafana_data: { }

networks:
  dsko-network: