version: '3.8'

services:
  app:
    image: spring-server:latest
    container_name: spring-server-container
    ports:
      - "8080:8080"
    depends_on:
      - redis
    # Redis 연결 정보를 도커 컴포즈 환경 변수로 주입
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data: